import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { homedir } from 'node:os';
const r = createRequire(import.meta.url);
const { chromium } = r(resolve(homedir(), 'Claude Helpers/Mission Control/node_modules/playwright/index.js'));
const B = process.argv[2] || 'http://localhost:8472/docs';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
const fail = m => { console.log('FAIL: ' + m); process.exitCode = 1; };
const ok = m => console.log('ok: ' + m);
await p.goto(`${B}/fleet.html`, { waitUntil: 'networkidle' });
const noStage = await p.$$eval('.stage', e => e.length);
noStage === 0 ? ok('the preview panel is gone') : fail(`${noStage} stage elements left`);
const w = await p.$eval('.list', e => Math.round(e.getBoundingClientRect().width));
w > 1300 ? ok(`the list is full width (${w}px of 1600)`) : fail(`list only ${w}px wide`);
await p.click('[data-view="grid"]');
await p.waitForTimeout(300);
const cols = await p.$eval('#rows', e => getComputedStyle(e).gridTemplateColumns.split(' ').length);
cols === 3 ? ok('grid view is exactly 3 per row') : fail(`grid has ${cols} columns, expected 3`);
const gridPressed = await p.$eval('[data-view="grid"]', e => e.getAttribute('aria-pressed'));
gridPressed === 'true' ? ok('grid button reports pressed') : fail(`aria-pressed=${gridPressed}`);
await p.reload({ waitUntil: 'networkidle' });
const stillGrid = await p.$eval('#rows', e => e.classList.contains('is-grid'));
stillGrid ? ok('the choice survives a reload') : fail('view reset to list after reload');
await p.click('[data-view="list"]');
await p.waitForTimeout(250);
const listRows = await p.$eval('#rows', e => e.classList.contains('is-grid'));
!listRows ? ok('switching back to list works') : fail('stuck in grid');
const visible = await p.$$eval('.row:not([hidden])', e => e.length);
visible === 20 ? ok('all 20 cars listed') : fail(`${visible} rows visible, expected 20`);
await p.click('.chip[data-cls="suv"]');
await p.waitForTimeout(200);
const suv = await p.$$eval('.row:not([hidden])', e => e.length);
suv === 3 ? ok('SUV filter shows exactly 3') : fail(`SUV shows ${suv}, expected 3`);
await b.close();
console.log(process.exitCode ? 'FLEET VIEW: FAILURES' : 'FLEET VIEW CLEAN');
